# Generated by Django 4.0.3 on 2022-05-05 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101)),
                ('location', models.CharField(max_length=300)),
                ('lat', models.CharField(max_length=101)),
                ('lng', models.CharField(max_length=101)),
                ('event_time', models.TimeField(null=True)),
                ('event_date', models.DateField(null=True)),
                ('time_created', models.TimeField(null=True)),
                ('date_created', models.DateField(null=True)),
                ('details', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
