# Generated by Django 4.0.4 on 2022-05-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_event_lat_event_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lng',
        ),
    ]
