# Generated by Django 4.0.4 on 2022-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_event_lat_event_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.CharField(max_length=101),
        ),
        migrations.AlterField(
            model_name='event',
            name='lng',
            field=models.CharField(max_length=101),
        ),
    ]
