# Generated by Django 4.0.4 on 2022-05-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_event_date_created_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Meet Up', 'meetup'), ('Party', 'party')], default='meet up', max_length=30),
        ),
    ]
