# Generated by Django 4.0.4 on 2022-05-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Meet Up', 'meet up'), ('Party', 'party')], default='meet up', max_length=30),
        ),
    ]
