# Generated by Django 4.0.3 on 2022-05-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Meet Up', 'meet up'), ('Party', 'party'), ('Music', 'music'), ('Community', 'community'), ('Professional', 'professional'), ('Social', 'social'), ('Sport', 'sport'), ('Lifestyle', 'lifestyle'), ('Religious', 'religious')], default=('Meet Up', 'meet up'), max_length=30),
        ),
    ]
